"""Create database

Revision ID: 0706aaf19b43
Revises: 
Create Date: 2026-03-13 11:17:25.927698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0706aaf19b43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batchjob',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column('user', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('submitted_on', sa.DateTime(), nullable=False),
        sa.Column('aws_job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('log_stream_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('status', sa.Enum('SUBMITTED', 'PENDING', 'RUNNABLE', 'STARTING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus'), nullable=False),
        sa.Column('viewed', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column('storage_backend', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uri', 'created_on', name='uq_file_uri_created_on')
    )
    op.create_table('pipeline',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('name')
    )
    op.create_table('project',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('project_id')
    )
    op.create_table('sequencingrun',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('run_date', sa.Date(), nullable=False),
        sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
        sa.Column('run_number', sa.Integer(), nullable=False),
        sa.Column('flowcell_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
        sa.Column('experiment_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('run_folder_uri', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('status', sa.Enum('IN_PROGRESS', 'UPLOADING', 'READY', 'RESYNC', name='runstatus'), nullable=True),
        sa.Column('run_time', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
        sa.Column('sequencing_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    settings_table = op.create_table('setting',
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendor',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_vendor_id'), 'vendor', ['vendor_id'], unique=True)
    op.create_table('workflow',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('definition_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
        sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['username'], ['users.username'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_username'), 'email_verification_tokens', ['username'], unique=False)
    op.create_table('filehash',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'algorithm', name='uq_filehash_file_algorithm')
    )
    op.create_table('filepipeline',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('pipeline_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'pipeline_id', name='uq_filepipeline')
    )
    op.create_table('fileproject',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'project_id', name='uq_fileproject')
    )
    op.create_table('filesequencingrun',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('sequencing_run_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.ForeignKeyConstraint(['sequencing_run_id'], ['sequencingrun.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'sequencing_run_id', name='uq_filesequencingrun')
    )
    op.create_table('filetag',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'key', name='uq_filetag_file_key')
    )
    op.create_table('oauth_providers',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('token_expires_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_providers_provider_user_id'), 'oauth_providers', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_oauth_providers_user_id'), 'oauth_providers', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['username'], ['users.username'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_username'), 'password_reset_tokens', ['username'], unique=False)
    op.create_table('pipelineattribute',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('pipeline_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pipeline_id', 'key', name='uq_pipeline_attr_key')
    )
    op.create_table('pipelineworkflow',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('pipeline_id', sa.Uuid(), nullable=False),
        sa.Column('workflow_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pipeline_id', 'workflow_id', name='uq_pipeline_workflow')
    )
    op.create_table('projectattribute',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id', 'project_id'),
        sa.UniqueConstraint('project_id', 'key')
    )
    op.create_table('refresh_tokens',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('revoked', sa.Boolean(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(['username'], ['users.username'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_username'), 'refresh_tokens', ['username'], unique=False)
    op.create_table('sample',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('sample_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sample_id', 'project_id')
    )
    op.create_table('workflowattribute',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('workflow_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowregistration',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('workflow_id', sa.Uuid(), nullable=False),
        sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['engine'], ['platform.name'], ),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workflow_id', 'engine', name='uq_workflow_engine')
    )
    op.create_table('workflowrun',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('workflow_id', sa.Uuid(), nullable=False),
        sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('external_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['engine'], ['platform.name'], ),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filesample',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('sample_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'sample_id', name='uq_filesample_file_sample')
    )
    op.create_table('fileworkflowrun',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'workflow_run_id', name='uq_fileworkflowrun')
    )
    op.create_table('qcrecord',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_on', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('sequencing_run_id', sa.Uuid(), nullable=True),
        sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            '(project_id IS NOT NULL AND sequencing_run_id IS NULL) OR (project_id IS NULL AND sequencing_run_id IS NOT NULL)',
            name='ck_qcrecord_scope'
        ),
        sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
        sa.ForeignKeyConstraint(['sequencing_run_id'], ['sequencingrun.id'], ),
        sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qcrecord_project_id'), 'qcrecord', ['project_id'], unique=False)
    op.create_index(op.f('ix_qcrecord_sequencing_run_id'), 'qcrecord', ['sequencing_run_id'], unique=False)
    op.create_index(op.f('ix_qcrecord_workflow_run_id'), 'qcrecord', ['workflow_run_id'], unique=False)
    op.create_table('sampleattribute',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('sample_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sample_id', 'key')
    )
    op.create_table('samplesequencingrun',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('sample_id', sa.Uuid(), nullable=False),
        sa.Column('sequencing_run_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
        sa.ForeignKeyConstraint(['sequencing_run_id'], ['sequencingrun.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sample_id', 'sequencing_run_id', name='uq_sample_seqrun')
    )
    op.create_table('workflowrunattribute',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fileqcrecord',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('qcrecord_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
        sa.ForeignKeyConstraint(['qcrecord_id'], ['qcrecord.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'qcrecord_id', name='uq_fileqcrecord')
    )
    op.create_table('qcmetric',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('qcrecord_id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('sequencing_run_id', sa.Uuid(), nullable=True),
        sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(['qcrecord_id'], ['qcrecord.id'], ),
        sa.ForeignKeyConstraint(['sequencing_run_id'], ['sequencingrun.id'], ),
        sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qcmetric_name'), 'qcmetric', ['name'], unique=False)
    op.create_index(op.f('ix_qcmetric_qcrecord_id'), 'qcmetric', ['qcrecord_id'], unique=False)
    op.create_index(op.f('ix_qcmetric_sequencing_run_id'), 'qcmetric', ['sequencing_run_id'], unique=False)
    op.create_index(op.f('ix_qcmetric_workflow_run_id'), 'qcmetric', ['workflow_run_id'], unique=False)
    op.create_table('qcrecordmetadata',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('qcrecord_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['qcrecord_id'], ['qcrecord.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('qcrecord_id', 'key', name='uq_qcrecordmetadata_record_key')
    )
    op.create_table('qcmetricsample',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('qc_metric_id', sa.Uuid(), nullable=False),
        sa.Column('sample_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(['qc_metric_id'], ['qcmetric.id'], ),
        sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('qc_metric_id', 'sample_id', name='uq_qcmetricsample_metric_sample')
    )
    op.create_index(op.f('ix_qcmetricsample_sample_id'), 'qcmetricsample', ['sample_id'], unique=False)
    op.create_table('qcmetricvalue',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('qc_metric_id', sa.Uuid(), nullable=False),
        sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('value_string', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value_numeric', sa.Float(), nullable=True),
        sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.ForeignKeyConstraint(['qc_metric_id'], ['qcmetric.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('qc_metric_id', 'key', name='uq_qcmetricvalue_metric_key')
    )

    # Seed system settings
    op.bulk_insert(settings_table, [
        {
            'key': 'DATA_BUCKET_URI',
            'value': '',
            'name': 'Data Bucket URI',
            'description': 'S3 bucket URI for storing NGS data files',
            'tags': [
                {'key': 'category', 'value': 'project settings'}
            ]
        },
        {
            'key': 'RESULTS_BUCKET_URI',
            'value': '',
            'name': 'Results Bucket URI',
            'description': 'S3 bucket URI for storing analysis results',
            'tags': [
                {'key': 'category', 'value': 'project settings'}
            ]
        },
        {
            'key': 'DEMUX_WORKFLOW_CONFIGS_BUCKET_URI',
            'value': '',
            'name': 'Demux Workflow Configs Bucket URI',
            'description': 'S3 bucket URI for storing demux workflow configuration files',
            'tags': [
                {'key': 'category', 'value': 'run settings'},
                {'key': 'type', 'value': 'aws-s3'}
            ]
        },
        {
            'key': 'MANIFEST_VALIDATION_LAMBDA',
            'value': '',
            'name': 'Manifest Validation Lambda',
            'description': 'ARN for the AWS Lambda function used to validate manifest files',
            'tags': [
                {'key': 'category', 'value': 'vendor settings'}
            ]
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qcmetricvalue')
    op.drop_index(op.f('ix_qcmetricsample_sample_id'), table_name='qcmetricsample')
    op.drop_table('qcmetricsample')
    op.drop_table('qcrecordmetadata')
    op.drop_index(op.f('ix_qcmetric_workflow_run_id'), table_name='qcmetric')
    op.drop_index(op.f('ix_qcmetric_sequencing_run_id'), table_name='qcmetric')
    op.drop_index(op.f('ix_qcmetric_qcrecord_id'), table_name='qcmetric')
    op.drop_index(op.f('ix_qcmetric_name'), table_name='qcmetric')
    op.drop_table('qcmetric')
    op.drop_table('fileqcrecord')
    op.drop_table('workflowrunattribute')
    op.drop_table('samplesequencingrun')
    op.drop_table('sampleattribute')
    op.drop_index(op.f('ix_qcrecord_workflow_run_id'), table_name='qcrecord')
    op.drop_index(op.f('ix_qcrecord_sequencing_run_id'), table_name='qcrecord')
    op.drop_index(op.f('ix_qcrecord_project_id'), table_name='qcrecord')
    op.drop_table('qcrecord')
    op.drop_table('fileworkflowrun')
    op.drop_table('filesample')
    op.drop_table('workflowrun')
    op.drop_table('workflowregistration')
    op.drop_table('workflowattribute')
    op.drop_table('sample')
    op.drop_index(op.f('ix_refresh_tokens_username'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('projectattribute')
    op.drop_table('pipelineworkflow')
    op.drop_table('pipelineattribute')
    op.drop_index(op.f('ix_password_reset_tokens_username'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_oauth_providers_user_id'), table_name='oauth_providers')
    op.drop_index(op.f('ix_oauth_providers_provider_user_id'), table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.drop_table('filetag')
    op.drop_table('filesequencingrun')
    op.drop_table('fileproject')
    op.drop_table('filepipeline')
    op.drop_table('filehash')
    op.drop_index(op.f('ix_email_verification_tokens_username'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('workflow')
    op.drop_index(op.f('ix_vendor_vendor_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('setting')
    op.drop_table('sequencingrun')
    op.drop_table('project')
    op.drop_table('platform')
    op.drop_table('pipeline')
    op.drop_table('file')
    op.drop_table('batchjob')
    # ### end Alembic commands ###
