"""Replace SequencingRun barcode with run_id

Revision ID: 1cc1c6be0725
Revises: 21274c7c470d
Create Date: 2026-04-21 21:09:14.797469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cc1c6be0725'
down_revision: Union[str, Sequence[str], None] = '21274c7c470d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencingrun', sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequencingrun', 'run_id')
    # ### end Alembic commands ###
