"""Convert run_number to str for ONT support

Revision ID: 21274c7c470d
Revises: b6ed07ea936e
Create Date: 2026-04-08 15:47:00.960505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21274c7c470d'
down_revision: Union[str, Sequence[str], None] = 'b6ed07ea936e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencingrun', 'run_number',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencingrun', 'run_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
