"""drop_workflowregistration_table

Revision ID: 266c22e168fc
Revises: 0706aaf19b43
Create Date: 2026-03-21 17:49:24.282900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '266c22e168fc'
down_revision: Union[str, Sequence[str], None] = '0706aaf19b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflowregistration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflowregistration',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('workflow_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('engine', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('external_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['engine'], ['platform.name'], name=op.f('workflowregistration_ibfk_1')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name=op.f('workflowregistration_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_workflow_engine'), 'workflowregistration', ['workflow_id', 'engine'], unique=True)
    # ### end Alembic commands ###
