"""Convert FileSample.sample_name to Samples.sample_id fk

Revision ID: 288c9a9ac0d3
Revises: f1a2b3c4d5e6
Create Date: 2026-02-20 14:20:02.241536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '288c9a9ac0d3'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'size',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('fileentity', 'entity_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PROJECT', 'RUN', 'SAMPLE', 'QCRECORD', name='fileentitytype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_fileentity_entity'), table_name='fileentity')
    op.drop_constraint(op.f('fileentity_ibfk_1'), 'fileentity', type_='foreignkey')
    op.create_foreign_key(None, 'fileentity', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('filehash_ibfk_1'), 'filehash', type_='foreignkey')
    op.create_foreign_key(None, 'filehash', 'file', ['file_id'], ['id'])
    op.add_column('filesample', sa.Column('sample_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_filesample_file_sample'), 'filesample', type_='unique')
    op.create_unique_constraint('uq_filesample_file_sample', 'filesample', ['file_id', 'sample_id'])
    op.drop_constraint(op.f('filesample_ibfk_1'), 'filesample', type_='foreignkey')
    op.create_foreign_key(None, 'filesample', 'file', ['file_id'], ['id'])
    op.create_foreign_key(None, 'filesample', 'sample', ['sample_id'], ['id'])
    op.drop_column('filesample', 'sample_name')
    op.drop_constraint(op.f('filetag_ibfk_1'), 'filetag', type_='foreignkey')
    op.create_foreign_key(None, 'filetag', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('qcmetric_ibfk_1'), 'qcmetric', type_='foreignkey')
    op.create_foreign_key(None, 'qcmetric', 'qcrecord', ['qcrecord_id'], ['id'])
    op.drop_constraint(op.f('qcmetricsample_ibfk_1'), 'qcmetricsample', type_='foreignkey')
    op.create_foreign_key(None, 'qcmetricsample', 'qcmetric', ['qc_metric_id'], ['id'])
    op.drop_index(op.f('ix_qcmetricvalue_key_numeric'), table_name='qcmetricvalue')
    op.drop_constraint(op.f('qcmetricvalue_ibfk_1'), 'qcmetricvalue', type_='foreignkey')
    op.create_foreign_key(None, 'qcmetricvalue', 'qcmetric', ['qc_metric_id'], ['id'])
    op.drop_constraint(op.f('qcrecordmetadata_ibfk_1'), 'qcrecordmetadata', type_='foreignkey')
    op.create_foreign_key(None, 'qcrecordmetadata', 'qcrecord', ['qcrecord_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qcrecordmetadata', type_='foreignkey')
    op.create_foreign_key(op.f('qcrecordmetadata_ibfk_1'), 'qcrecordmetadata', 'qcrecord', ['qcrecord_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'qcmetricvalue', type_='foreignkey')
    op.create_foreign_key(op.f('qcmetricvalue_ibfk_1'), 'qcmetricvalue', 'qcmetric', ['qc_metric_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_qcmetricvalue_key_numeric'), 'qcmetricvalue', ['key', 'value_numeric'], unique=False)
    op.drop_constraint(None, 'qcmetricsample', type_='foreignkey')
    op.create_foreign_key(op.f('qcmetricsample_ibfk_1'), 'qcmetricsample', 'qcmetric', ['qc_metric_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'qcmetric', type_='foreignkey')
    op.create_foreign_key(op.f('qcmetric_ibfk_1'), 'qcmetric', 'qcrecord', ['qcrecord_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'filetag', type_='foreignkey')
    op.create_foreign_key(op.f('filetag_ibfk_1'), 'filetag', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.add_column('filesample', sa.Column('sample_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'filesample', type_='foreignkey')
    op.drop_constraint(None, 'filesample', type_='foreignkey')
    op.create_foreign_key(op.f('filesample_ibfk_1'), 'filesample', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_filesample_file_sample', 'filesample', type_='unique')
    op.create_unique_constraint(op.f('uq_filesample_file_sample'), 'filesample', ['file_id', 'sample_name'])
    op.drop_column('filesample', 'sample_id')
    op.drop_constraint(None, 'filehash', type_='foreignkey')
    op.create_foreign_key(op.f('filehash_ibfk_1'), 'filehash', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'fileentity', type_='foreignkey')
    op.create_foreign_key(op.f('fileentity_ibfk_1'), 'fileentity', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_fileentity_entity'), 'fileentity', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('fileentity', 'entity_type',
               existing_type=sa.Enum('PROJECT', 'RUN', 'SAMPLE', 'QCRECORD', name='fileentitytype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('file', 'size',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
