"""remove workflow run tables, add version attributes, auto-increment version, platform uuid PK

Revision ID: 38160a9eca15
Revises: 8a5d5a8bb9f6
Create Date: 2026-04-29 13:44:37.478105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38160a9eca15'
down_revision: Union[str, Sequence[str], None] = '8a5d5a8bb9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    1. Drop WorkflowRun-related tables and convert FK references to plain UUIDs.
       Workflow run tracking is now handled by an external database.
    2. Create WorkflowVersionAttribute table for key-value metadata on versions.
    3. Change WorkflowVersion.version from VARCHAR to INTEGER (auto-increment).
    4. Add UUID primary key to Platform table (name becomes unique constraint).

    Order: FK constraints first, then dependent tables, then parent table.
    """
    # --- Part 1: Remove WorkflowRun tables ---

    # 1a. Drop FK constraints that reference workflowrun
    op.drop_constraint('qcmetric_ibfk_3', 'qcmetric', type_='foreignkey')
    op.drop_constraint('qcrecord_ibfk_3', 'qcrecord', type_='foreignkey')

    # 1b. Drop dependent tables (drop_table handles indexes implicitly)
    op.drop_table('fileworkflowrun')
    op.drop_table('workflowrunattribute')

    # 1c. Drop the parent table last
    op.drop_table('workflowrun')

    # --- Part 2: Create WorkflowVersionAttribute table ---

    op.create_table(
        'workflowversionattribute',
        sa.Column('id', sa.CHAR(length=32), nullable=False),
        sa.Column('workflow_version_id', sa.CHAR(length=32), nullable=False),
        sa.Column('key', sa.VARCHAR(length=255), nullable=False),
        sa.Column('value', sa.VARCHAR(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ['workflow_version_id'], ['workflowversion.id'],
            name='fk_wfverattr_workflowversion',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    # --- Part 3: Change WorkflowVersion.version from VARCHAR to INTEGER ---

    op.alter_column(
        'workflowversion',
        'version',
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='version::integer',
    )

    # --- Part 4: Add UUID primary key to Platform table ---
    # Currently platform.name is the PK. We add a UUID id column as the new PK
    # and demote name to a unique constraint.
    # Note: table is assumed empty (no existing rows to backfill).

    # 4a. Drop the existing PK on name
    op.execute("ALTER TABLE platform DROP PRIMARY KEY")

    # 4b. Add the id column (CHAR(32) for UUID storage, NOT NULL)
    op.add_column(
        'platform',
        sa.Column('id', sa.CHAR(length=32), nullable=False),
    )

    # 4c. Set id as the new primary key
    op.create_primary_key('pk_platform', 'platform', ['id'])

    # 4d. Add unique constraint on name
    op.create_unique_constraint('uq_platform_name', 'platform', ['name'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('qcrecord_ibfk_3'), 'qcrecord', 'workflowrun', ['workflow_run_id'], ['id'])
    op.create_foreign_key(op.f('qcmetric_ibfk_3'), 'qcmetric', 'workflowrun', ['workflow_run_id'], ['id'])
    op.create_table('workflowrunattribute',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('workflow_run_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], name=op.f('workflowrunattribute_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('workflowrun',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('engine', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('external_run_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('workflow_version_id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['engine'], ['platform.name'], name='workflowrun_ibfk_1'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflowversion.id'], name='fk_wfrun_workflowversion'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fileworkflowrun',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('file_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('workflow_run_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fileworkflowrun_ibfk_1')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflowrun.id'], name=op.f('fileworkflowrun_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_fileworkflowrun'), 'fileworkflowrun', ['file_id', 'workflow_run_id'], unique=True)
    # ### end Alembic commands ###
