"""Add workflow tables

Revision ID: 424e0175e008
Revises: 8cc07dcfe575
Create Date: 2025-12-23 10:07:28.526916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '424e0175e008'
down_revision: Union[str, Sequence[str], None] = '8cc07dcfe575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engine_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowattribute',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflowattribute')
    op.drop_table('workflow')
    # ### end Alembic commands ###
