"""Convert run status to enum

Revision ID: 43c1f122cf7f
Revises: 45a78144014d
Create Date: 2025-09-20 08:51:49.166094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43c1f122cf7f'
down_revision: Union[str, Sequence[str], None] = '45a78144014d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencingrun', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('IN_PROGRESS', 'UPLOADING', 'READY', 'RESYNC', name='runstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencingrun', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'UPLOADING', 'READY', 'RESYNC', name='runstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
