"""Creating SequencingRun table

Revision ID: 45a78144014d
Revises: a1245f51f52c
Create Date: 2025-08-18 18:51:11.800455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45a78144014d'
down_revision: Union[str, Sequence[str], None] = 'a1245f51f52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencingrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('flowcell_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('experiment_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('run_folder_uri', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('run_time', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequencingrun')
    # ### end Alembic commands ###
