"""Add created_by, created_at, last_modified to Project table

Revision ID: 49e7d06e7eb4
Revises: 983b2235ef87
Create Date: 2026-05-30 11:59:52.816863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import re

# revision identifiers, used by Alembic.
revision: str = '49e7d06e7eb4'
down_revision: Union[str, Sequence[str], None] = '983b2235ef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def back_fill():
    """Backfill created_by, created_at, and last_modified from projectattribute entries."""
    from datetime import datetime, timezone
    from sqlmodel import Session, select
    from api.project.models import Project, ProjectAttribute

    # Use alembic's connection to avoid lock contention with DDL
    bind = op.get_bind()
    with Session(bind=bind) as session:
        # Get all projects ordered by project_id
        projects = session.exec(select(Project).order_by(Project.project_id)).all()

        pattern = r"^P-(\d{4})(\d{2})(\d{2})-(\d{4})$"

        # For each project, get the created_by and createdate values from the projectattribute table
        for project in projects:
            # Handle created_by
            created_by_stmt = select(ProjectAttribute.value).where(
                ProjectAttribute.project_id == project.id,
                ProjectAttribute.key.in_(["createby", "createdby"])
            )
            created_by_value = session.exec(created_by_stmt).first()

            # Fallback for projects without a matching attribute
            project.created_by = created_by_value or "unknown"

            # project.project_id is format is P-YYYYMMDD-#####
            # Parse out year, month, date to create a datetime object for created_at
            match = re.match(pattern, project.project_id)
            if match:
                year, month, day = match.group(1), match.group(2), match.group(3)
                try:
                    created_at_value = datetime(int(year), int(month), int(day), tzinfo=timezone.utc)
                except ValueError:
                    created_at_value = datetime(1970, 1, 1, tzinfo=timezone.utc)
            else:
                created_at_value = datetime(1970, 1, 1, tzinfo=timezone.utc)

            project.created_at = created_at_value
            project.last_modified = project.created_at
            session.add(project)


def upgrade() -> None:
    """Upgrade schema."""
    # Phase 1: Add columns as NULLABLE
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('last_modified', sa.DateTime(), nullable=True))

    # Phase 2: Backfill existing rows
    back_fill()

    # Phase 3: Alter columns to be NOT NULL
    op.alter_column('project', 'created_at', nullable=False, existing_type=sa.DateTime())
    op.alter_column('project', 'created_by', nullable=False, existing_type=sqlmodel.sql.sqltypes.AutoString())
    op.alter_column('project', 'last_modified', nullable=False, existing_type=sa.DateTime())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'last_modified')
    op.drop_column('project', 'created_by')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
