"""Add created_by, created_at, last_modified to Project table

Revision ID: 49e7d06e7eb4
Revises: 983b2235ef87
Create Date: 2026-05-30 11:59:52.816863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49e7d06e7eb4'
down_revision: Union[str, Sequence[str], None] = '983b2235ef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def back_fill():
    """Backfill created_by, created_at, and last_modified using pure SQL."""
    bind = op.get_bind()
    
    # Update created_by from projectattribute table in a single query
    bind.execute(sa.text("""
        UPDATE project
        SET created_by = COALESCE(
            (
                SELECT value
                FROM projectattribute
                WHERE projectattribute.project_id = project.id
                AND LOWER(`key`) IN ('createby', 'createdby', 'businessowner', 'Business Owner')
                LIMIT 1
            ),
            'unknown'
        )
    """))
    
    # Update created_at and last_modified by parsing project_id in a single query
    # project_id format is P-YYYYMMDD-####
    # Extract date using SUBSTRING and convert using STR_TO_DATE (MySQL)
    bind.execute(sa.text("""
        UPDATE project
        SET
            created_at = CASE
                WHEN project_id REGEXP '^P-[0-9]{8}-[0-9]{4}$'
                    AND SUBSTRING(project_id, 3, 8) != '00000000'
                    AND STR_TO_DATE(SUBSTRING(project_id, 3, 8), '%Y%m%d') IS NOT NULL
                THEN
                    STR_TO_DATE(SUBSTRING(project_id, 3, 8), '%Y%m%d')
                ELSE
                    '1970-01-01 00:00:00'
            END,
            last_modified = CASE
                WHEN project_id REGEXP '^P-[0-9]{8}-[0-9]{4}$'
                    AND SUBSTRING(project_id, 3, 8) != '00000000'
                    AND STR_TO_DATE(SUBSTRING(project_id, 3, 8), '%Y%m%d') IS NOT NULL
                THEN
                    STR_TO_DATE(SUBSTRING(project_id, 3, 8), '%Y%m%d')
                ELSE
                    '1970-01-01 00:00:00'
            END
    """))


def upgrade() -> None:
    """Upgrade schema."""
    # Phase 1: Add columns as NULLABLE
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('last_modified', sa.DateTime(), nullable=True))

    # Phase 2: Backfill existing rows
    back_fill()

    # Phase 3: Alter columns to be NOT NULL
    op.alter_column('project', 'created_at', nullable=False, existing_type=sa.DateTime())
    op.alter_column('project', 'created_by', nullable=False, existing_type=sqlmodel.sql.sqltypes.AutoString())
    op.alter_column('project', 'last_modified', nullable=False, existing_type=sa.DateTime())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'last_modified')
    op.drop_column('project', 'created_by')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
