"""add original_barcode to sequencingrun

Revision ID: 5d121c106e1a
Revises: 21274c7c470d
Create Date: 2026-04-17 15:54:54.117927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d121c106e1a'
down_revision: Union[str, Sequence[str], None] = '21274c7c470d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencingrun', sa.Column('original_barcode', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequencingrun', 'original_barcode')
    # ### end Alembic commands ###
