"""

Revision ID: 635d4dcee57b
Revises: 45a78144014d
Create Date: 2025-09-19 21:27:21.337650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '635d4dcee57b'
down_revision: Union[str, Sequence[str], None] = '45a78144014d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencingrun', sa.Column('run_folder_uri', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('sequencingrun', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('IN_PROGRESS', 'UPLOADING', 'READY', 'RESYNC', name='runstatus'),
               existing_nullable=True)
    op.drop_column('sequencingrun', 's3_run_folder_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencingrun', sa.Column('s3_run_folder_path', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('sequencingrun', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'UPLOADING', 'READY', 'RESYNC', name='runstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('sequencingrun', 'run_folder_uri')
    # ### end Alembic commands ###
