"""add_vendor_table

Revision ID: 8cc07dcfe575
Revises: 43c1f122cf7f
Create Date: 2025-10-13 22:29:13.241073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cc07dcfe575'
down_revision: Union[str, Sequence[str], None] = '43c1f122cf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_vendor_id'), 'vendor', ['vendor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_vendor_id'), table_name='vendor')
    op.drop_table('vendor')
    # ### end Alembic commands ###
