"""add VENDOR_INGESTION_CONFIG setting

Revision ID: 906fc3906e9d
Revises: 2a06fb0eebbb
Create Date: 2026-02-25 10:26:17.487598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column

# revision identifiers, used by Alembic.
revision: str = '906fc3906e9d'
down_revision: Union[str, Sequence[str], None] = '2a06fb0eebbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Define the settings table for data insertion
    setting_table = table('setting',
        column('key', sa.String),
        column('value', sa.String),
        column('name', sa.String),
        column('description', sa.String),
        column('tags', sa.JSON),
    )
    # Insert system setting
    op.bulk_insert(setting_table, [
        {
            'key': 'VENDOR_INGESTION_CONFIG',
            'value': '',
            'name': 'Vendor Ingestion Config',
            'description': 'Configuration for vendor ingestion',
            'tags': [
                {'key': 'category', 'value': 'project settings'}
            ]
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM setting WHERE `key` = 'VENDOR_INGESTION_CONFIG'"
    )
    # ### end Alembic commands ###
