"""add_files_table

Revision ID: 95817dee746c
Revises: c955364e5391
Create Date: 2025-09-20 14:28:45.987919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95817dee746c'
down_revision: Union[str, Sequence[str], None] = '43c1f122cf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('file_type', sa.Enum('FASTQ', 'BAM', 'VCF', 'SAMPLESHEET', 'METRICS', 'REPORT', 'LOG', 'IMAGE', 'DOCUMENT', 'OTHER', name='filetype'), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('entity_type', sa.Enum('PROJECT', 'RUN', name='entitytype'), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('storage_backend', sa.Enum('LOCAL', 'S3', 'AZURE', 'GCS', name='storagebackend'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
