"""add created_at and updated_at to sample table

Revision ID: 983b2235ef87
Revises: 21274c7c470d
Create Date: 2026-04-21 21:25:07.999140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '983b2235ef87'
down_revision: Union[str, Sequence[str], None] = '38160a9eca15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sample', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'updated_at')
    op.drop_column('sample', 'created_at')
    # ### end Alembic commands ###
