"""Update sample project_id to string

Revision ID: a1245f51f52c
Revises: 8f2133e8188e
Create Date: 2025-08-14 08:16:47.880144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1245f51f52c'
down_revision: Union[str, Sequence[str], None] = '8f2133e8188e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'project_id')
    )
    op.create_table('sampleattribute',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sampleattribute')
    op.drop_table('sample')
    # ### end Alembic commands ###
