"""Add run_id unique constraint to sequencingrun table

Revision ID: b37c101f44a0
Revises: 1cc1c6be0725
Create Date: 2026-05-01 17:54:08.677285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b37c101f44a0'
down_revision: Union[str, Sequence[str], None] = '1cc1c6be0725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sequencingrun_run_id', 'sequencingrun', ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sequencingrun_run_id', 'sequencingrun', type_='unique')
    # ### end Alembic commands ###
