"""Remove aws_job_id from BatchJob

Revision ID: b6ed07ea936e
Revises: ebc60b8b4a17
Create Date: 2026-04-07 14:37:26.034587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6ed07ea936e'
down_revision: Union[str, Sequence[str], None] = 'ebc60b8b4a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batchjob', 'id',
               existing_type=mysql.CHAR(length=32),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.drop_column('batchjob', 'aws_job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batchjob', sa.Column('aws_job_id', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('batchjob', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
