"""add batch job table

Revision ID: d89d27d47634
Revises: 9e9141c05908
Create Date: 2026-01-14 19:52:49.718948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd89d27d47634'
down_revision: Union[str, Sequence[str], None] = '9e9141c05908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batchjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=False),
    sa.Column('aws_job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('log_stream_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'PENDING', 'RUNNABLE', 'STARTING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batchjob')
    # ### end Alembic commands ###
