"""Add missing db default settings

Revision ID: ebc60b8b4a17
Revises: 0706aaf19b43
Create Date: 2026-04-02 19:05:17.682344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebc60b8b4a17'
down_revision: Union[str, Sequence[str], None] = '0706aaf19b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Define a reference to the existing settings table
    settings_table = sa.table('setting',
        sa.column('key', sa.String),
        sa.column('value', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('tags', sa.JSON),
    )
    op.bulk_insert(settings_table, [
        {
            'key': 'PROJECT_WORKFLOW_CONFIGS_BUCKET_URI',
            'value': '',
            'name': 'Project Workflow Configs Bucket URI',
            'description': 'S3 bucket URI for storing project workflow configuration files',
            'tags': [
                {'key': 'category', 'value': 'project settings'}
            ]
        },
        {
            'key': 'VENDOR_INGESTION_CONFIG',
            'value': '',
            'name': 'Vendor Ingestion Config',
            'description': 'Configuration for vendor ingestion',
            'tags': [
                {'key': 'category', 'value': 'project settings'}
            ]
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    settings_table = sa.table('setting',
        sa.column('key', sa.String),
        sa.column('value', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('tags', sa.JSON),
    )
    op.execute(
        settings_table.delete().where(
            settings_table.c.key.in_([
                'PROJECT_WORKFLOW_CONFIGS_BUCKET_URI',
                'VENDOR_INGESTION_CONFIG'
            ])
        )
    )
    # ### end Alembic commands ###
