"""Create SequencingRun table

Revision ID: edc966290ae2
Revises: a1245f51f52c
Create Date: 2025-08-16 10:00:08.303350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'edc966290ae2'
down_revision: Union[str, Sequence[str], None] = 'a1245f51f52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencingrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('run_number', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('flowcell_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('experiment_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('s3_run_folder_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('run_time', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequencingrun')
    # ### end Alembic commands ###
