"""Simplify File model

Revision ID: f46192b55af8
Revises: 95817dee746c
Create Date: 2025-10-01 10:22:34.901183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f46192b55af8'
down_revision: Union[str, Sequence[str], None] = '95817dee746c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('destination_uri', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False))
    op.drop_column('file', 'original_filename')
    op.drop_column('file', 'is_public')
    op.drop_column('file', 'is_archived')
    op.drop_column('file', 'storage_backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('storage_backend', mysql.ENUM('LOCAL', 'S3', 'AZURE', 'GCS'), nullable=False))
    op.add_column('file', sa.Column('is_archived', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('file', 'destination_uri')
    # ### end Alembic commands ###
