"""increase size of project name column

Revision ID: ae9ffcb4bc5b
Revises: 3ee54f8f02d6
Create Date: 2025-04-22 22:33:36.722935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae9ffcb4bc5b'
down_revision = '3ee54f8f02d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
