"""
Models for the Runs API
"""
from typing import List, Optional, Any, Dict, TYPE_CHECKING
import uuid
from datetime import datetime, date, timezone
from enum import Enum
from sqlmodel import SQLModel, Field, Relationship, UniqueConstraint
from pydantic import ConfigDict, field_validator, BaseModel, model_validator

from api.jobs.models import AwsBatchConfig

if TYPE_CHECKING:
    from api.qcmetrics.models import QCRecord  # noqa: F401


class RunStatus(str, Enum):
    """Enumeration of valid sequencing run statuses"""
    IN_PROGRESS = "In Progress"
    UPLOADING = "Uploading"
    READY = "Ready"
    RESYNC = "Resync"


class SequencingRun(SQLModel, table=True):
    """
    This class/table represents a (Illumina/ONT) sequencing run

    Illumina run metadata is sourced from RunInfo.xml, which is
    generated by the instrument and stored with the run.
    It contains:
        - runinfo_version
        - run_id
        - run_number
        - flowcell
        - machine_id
        - run_date
    Most of the time, the run_id contains the flowcell id, but not
    always. It may or may not be part of the folder name.
    Additionally, run_id may contain the flowcell as a substring.
    """

    # Searchable is a field used for Elasticsearch
    # This field is iterated on to identify what fields are searchable
    # or inserted into the ElasticSearch index.
    __searchable__ = ["run_id", "flowcell_id", "experiment_name", "run_folder_uri"]

    id: uuid.UUID | None = Field(default_factory=uuid.uuid4, primary_key=True)

    run_id: str = Field(max_length=255, unique=True)
    run_date: date
    machine_id: str = Field(max_length=25)
    # For ONT, this could be non-numeric,  For Illumina, this is a number.
    run_number: str = Field(max_length=50)
    flowcell_id: str = Field(max_length=25)
    experiment_name: str | None = Field(default=None, max_length=255)
    run_folder_uri: str | None = Field(default=None, max_length=255)
    status: RunStatus | None = Field(default=None)
    # For ONT, we have an additional field for run_time since it's part of the barcode
    run_time: str | None = Field(default=None, max_length=4)
    # TBD: Convert this to an enum or separate table if we want to enforce a set of allowed platforms
    sequencing_platform: str | None = Field(default=None, max_length=50)  # e.g., "Illumina", "ONT"

    # Relationships
    qcrecords: List["QCRecord"] = Relationship(back_populates="sequencing_run")

    model_config = ConfigDict(from_attributes=True)

    def to_dict(self):
        ''' Returns a dictionary representation of the object '''
        data = {
            "run_id": self.run_id,
            "run_date": self.run_date.strftime("%Y-%m-%d") if self.run_date else None,
            "machine_id": self.machine_id,
            "run_number": self.run_number,
            "run_time": self.run_time,
            "flowcell_id": self.flowcell_id,
            "experiment_name": self.experiment_name,
            "run_folder_uri": self.run_folder_uri,
            "status": self.status.value if self.status else None,
        }
        return data

    def __repr__(self):
        return f"<SequencingRun {self.run_id}>"


class SequencingRunCreate(SQLModel):
    run_id: str
    run_date: date
    machine_id: str
    run_number: str
    flowcell_id: str
    experiment_name: str | None = None
    run_folder_uri: str | None = None
    status: RunStatus | None = None
    run_time: str | None = None

    model_config = ConfigDict(extra="forbid")

    @field_validator('run_time', mode='before')
    @classmethod
    def preprocess_run_time(cls, v):
        """Convert empty string to None before validation"""
        return None if v == "" else v

    @field_validator('run_time')
    @classmethod
    def validate_run_time_format(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None

        if not isinstance(v, str) or len(v) != 4 or not v.isdigit():
            raise ValueError('run_time must be exactly 4 digits (HHMM format)')

        hours, minutes = int(v[:2]), int(v[2:])
        if not (0 <= hours <= 23) or not (0 <= minutes <= 59):
            raise ValueError('Hours must be 00-23, minutes must be 00-59')

        return v


class SequencingRunUpdateRequest(SQLModel):
    run_status: RunStatus

    model_config = ConfigDict(extra="forbid")


class SequencingRunPublic(SQLModel):
    run_id: str
    run_date: date
    machine_id: str
    run_number: str
    flowcell_id: str
    experiment_name: str | None
    run_folder_uri: str | None
    status: RunStatus | None
    run_time: str | None


class SequencingRunsPublic(SQLModel):
    data: list[SequencingRunPublic]
    total_items: int
    total_pages: int
    current_page: int
    per_page: int
    has_next: bool
    has_prev: bool


class IlluminaSampleSheetResponseModel(SQLModel):
    Summary: dict[str, str] | None = None
    Header: dict[str, str] | None = None
    Reads: list[int] | None = None
    Settings: dict[str, str] | None = None
    Data: list[dict[str, str]] | None = None
    DataCols: list[str] | None = None


# Helper types for IlluminaMetricsResponseModel
class ReadMetricsType(SQLModel):
    ReadNumber: int | None = None
    Yield: int | None = None
    YieldQ30: int | None = None
    QualityScoreSum: int | None = None
    TrimmedBases: int | None = None


class ReadInfo(SQLModel):
    Number: int | None = None
    NumCycles: int | None = None
    IsIndexedRead: bool | None = None


class ReadInfosForLane(SQLModel):
    LaneNumber: int | None = None
    ReadInfos: list[ReadInfo] | None = None


class IndexMetric(SQLModel):
    IndexSequence: str | None = None
    MismatchCounts: dict[str, int] | None = None


class DemuxResult(SQLModel):
    SampleId: str
    SampleName: str | None = None
    IndexMetrics: list[IndexMetric] | None = None
    NumberReads: int = 0
    Yield: int | None = None
    ReadMetrics: list[ReadMetricsType] = None


class UndeterminedType(SQLModel):
    NumberReads: int | None = None
    Yield: int | None = None
    ReadMetrics: list[ReadMetricsType] | None = None


class ConversionResult(SQLModel):
    LaneNumber: int
    TotalClustersRaw: int
    TotalClustersPF: int
    Yield: int | None = None
    DemuxResults: list[DemuxResult] | None = None
    Undetermined: UndeterminedType | None = None


class UnknownBarcode(SQLModel):
    Lane: int | None = None
    Barcodes: dict[str, int] | None = None


class IlluminaMetricsResponseModel(SQLModel):
    Flowcell: str | None = None
    RunNumber: int | None = None
    RunId: str | None = None
    ReadInfosForLanes: list[ReadInfosForLane] | None = None
    ConversionResults: list[ConversionResult] | None = None
    UnknownBarcodes: list[UnknownBarcode] | None = None


class InputType(str, Enum):
    ENUM = "Enum"
    STRING = "String"
    INTEGER = "Integer"
    BOOLEAN = "Boolean"


class DemuxWorkflowConfigInput(BaseModel):
    name: str
    desc: str
    type: InputType
    required: bool = False
    default: Optional[Any] = None
    options: Optional[List[str]] = None

    @model_validator(mode='after')
    def validate_enum_has_options(self):
        if self.type == InputType.ENUM and not self.options:
            raise ValueError("Input type 'Enum' must have options defined")
        return self


class DemuxWorkflowTag(BaseModel):
    name: str


class DemuxWorkflowConfig(BaseModel):
    version: int
    workflow_id: str
    workflow_name: str
    workflow_description: str
    inputs: List[DemuxWorkflowConfigInput]
    help: str
    tags: List[DemuxWorkflowTag]
    aws_batch: Optional[AwsBatchConfig] = None


class DemuxWorkflowSubmitBody(BaseModel):
    workflow_id: str
    run_id: str
    inputs: Dict[str, Any]


# ---------------------------------------------------------------------------
# Sample ↔ SequencingRun junction table (Phase 1)
# ---------------------------------------------------------------------------

class SampleSequencingRun(SQLModel, table=True):
    """Many-to-many junction between Sample and SequencingRun."""
    __tablename__ = "samplesequencingrun"
    __table_args__ = (
        UniqueConstraint("sample_id", "sequencing_run_id", name="uq_sample_seqrun"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    sample_id: uuid.UUID = Field(foreign_key="sample.id")
    sequencing_run_id: uuid.UUID = Field(foreign_key="sequencingrun.id")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: str


class SampleSequencingRunCreate(SQLModel):
    sample_id: uuid.UUID


class SampleSequencingRunPublic(SQLModel):
    id: uuid.UUID
    sample_id: uuid.UUID
    sequencing_run_id: uuid.UUID
    created_at: datetime
    created_by: str


class RunSampleCleanupResponse(SQLModel):
    """Response model for bulk sample/file cleanup on a run (re-demux scenario)."""
    run_id: str
    associations_removed: int
    files_deleted: int
    samples_deleted: int
    samples_preserved: int
    qcrecords_deleted: int = 0
