name: Unit test and coverage report
# Run unit tests and generate coverage report

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      #- name: Verify Python and pytest installation
      #  run: |
      #    which python
      #    which pytest
      #    python --version
      #    pytest --version

      - name: Run tests
        run: uv run make test

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true

