name: Unit test and coverage report
# Run unit tests and generate coverage report

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read Python version from .python-version
        id: read_python
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.read_python.outputs.version }}

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies (including dev) from lockfile
        run: uv sync --locked

      - name: Install pytest and pytest-cov
        run: uv pip install pytest pytest-cov

      - name: Add Python bin directory to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Verify Python and pytest installation
        run: |
          which python
          which pytest
          python --version
          pytest --version

      - name: Run tests
        run: python -m pytest -xsv --cov

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true

